### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by moedn** [benedictdudel/pandoc-letter-din5008#14]
1. thousand thanks for this great template :tada: 

2. but without a license, this work is not open source and hence not (officially) available for others

I'll suggest the current creative commons ShareAlike in #15 :)

**Comment by NMarkgraf** [comment]
CC-BY-SA .. well all derived work is now also under CC-BY-SA, was that what you want? ;-)
Why not LGPL?

**Comment by moedn** [comment]
:) yes, but that's rather a personal choice. I prefer strong copyleft over permissive licenses to keep the whole chain open. That way you're also never excluded from further development of your work.
I know that some companies try to avoid strong copyleft licensed work by all costs, but in few cases there's a deep rationale behind it.

`LGPL-3.0-or-later` of course also works.

Edit: This question may also depend on your local ecosystem. If you want to merge/include related work from others, this will _only_ be possible when that work also has a permissive license. You can't re-license e.g. GPL work under LPGL. That's why LibreOffice (GPL) can merge features from OpenOffice (Apache), but not the other way around
