### ISSUE TITLE
Use plural of *Anlagen* if more than one document is enclosed

### ISSUE THREAD

**Issue by paulmenzel** [benedictdudel/pandoc-letter-din5008#16]
encludes: Muster, Muster, Muster

currently results in

    Anlage: Muster, Muster, Muster

where it should use the plural form *Anlagen*.

**Comment by benedictdudel** [comment]
I added the wording _Anlage(n)_ as a workaround. Unfortunately, it is not possible with pandoc to determine the number of items in an array according to this issue https://github.com/jgm/pandoc/issues/2416.
