### ISSUE TITLE
Tables left aligned?

### ISSUE THREAD

**Issue by durcheinandr** [benedictdudel/pandoc-letter-din5008#3]
Thanks for this template. Any hints how to align tables to the left instead of showing centered?

**Comment by benedictdudel** [comment]
Unfortunatly this isn't possible to control via pandoc. You can change the following [line](https://github.com/benedictdudel/pandoc-letter-din5008/blob/b2db002e5abc2d6b1ce106d5d9b084d69a3f05a0/letter.latex#L20) in the template to `\usepackage{longtable}\setlength{\LTleft}{2em}`. This would left align all tables `2em` from the left.

Thank you for your kind words. I hope I could help you out.

**Comment by durcheinandr** [comment]
Thanks. Works as expected.
